version: '3.7'

services:

  lb:
    image: traefik:2.2.1
    container_name: lb
    ports:
      - 3000:80
    command:
      - --providers.docker
      - --log.level=Info
      - --accessLog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    environment:
      POSTGRES_DB: hrsa
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./api/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  api:
    environment:
      FLASK_APP: api.py
      FLASK_ENV: development
      FLASK_DEBUG: 'true'
      DATABASE_URI: postgres://postgres:postgres@db:5432/hrsa
    container_name: api
    tty: true
    entrypoint: ./entrypoint.sh
    volumes:
      - ./api:/api
      - ./etl/data/:/data
    labels:
      traefik.http.routers.api.rule: PathPrefix(`/api`)
      traefik.http.routers.api.priority: 100

  dashboard:
    container_name: dashboard
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    tty: true
    command: yarn start
    volumes:
      - ./dashboard:/dashboard
      - node_modules:/dashboard/node_modules
    labels:
      traefik.http.routers.dashboard.rule: HostRegexp(`{catchAll:.*}`)

volumes:
  db_data:
  node_modules:
